In [50]:
# get data
import pandas as pd
df = pd.read_csv("socioeconomic_voting.csv")
df

,State,County Name,FIPS,Unemployment Rate 2020,County Median Household Income (2021),Urban Influence Code 2013,County Income Percentile Within State (2021),Bachelor's Degree or Higher Percentage (2018-2022),Party,Vote Percentage
0,ALABAMA,AUTAUGA,1001,5.3,66444.0,2.0,0.955224,29.6,REPUBLICAN,71.436802
1,ALABAMA,BALDWIN,1003,6.1,65658.0,2.0,0.940299,32.6,REPUBLICAN,76.171373
2,ALABAMA,BARBOUR,1005,7.7,38649.0,6.0,0.164179,11.9,REPUBLICAN,53.451226
3,ALABAMA,BIBB,1007,7.3,48454.0,1.0,0.611940,10.9,REPUBLICAN,78.426264
4,ALABAMA,BLOUNT,1009,4.5,56894.0,1.0,0.895522,14.7,REPUBLICAN,89.571553
...,...,...,...,...,...,...,...,...,...,...
3110,WYOMING,SWEETWATER,56037,7.5,74677.0,8.0,0.826087,20.0,REPUBLICAN,73.236316
3111,WYOMING,TETON,56039,6.0,102709.0,8.0,1.000000,60.3,DEMOCRAT,66.599040
3112,WYOMING,UINTA,56041,6.4,70162.0,8.0,0.739130,19.1,REPUBLICAN,79.247278
3113,WYOMING,WASHAKIE,56043,5.3,62176.0,11.0,0.391304,21.1,REPUBLICAN,80.481151
3114,WYOMING,WESTON,56045,3.9,62509.0,9.0,0.434783,17.6,REPUBLICAN,87.275281

In [51]:
# data prep
y = df["County Median Household Income (2021)"]
y
x = df.drop(["County Median Household Income (2021)", "Party", "State", "County Name"], axis=1)
x

,FIPS,Unemployment Rate 2020,Urban Influence Code 2013,County Income Percentile Within State (2021),Bachelor's Degree or Higher Percentage (2018-2022),Vote Percentage
0,1001,5.3,2.0,0.955224,29.6,71.436802
1,1003,6.1,2.0,0.940299,32.6,76.171373
2,1005,7.7,6.0,0.164179,11.9,53.451226
3,1007,7.3,1.0,0.611940,10.9,78.426264
4,1009,4.5,1.0,0.895522,14.7,89.571553
...,...,...,...,...,...,...
3110,56037,7.5,8.0,0.826087,20.0,73.236316
3111,56039,6.0,8.0,1.000000,60.3,66.599040
3112,56041,6.4,8.0,0.739130,19.1,79.247278
3113,56043,5.3,11.0,0.391304,21.1,80.481151
3114,56045,3.9,9.0,0.434783,17.6,87.275281

In [52]:
# split data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
x_test
x_train

,FIPS,Unemployment Rate 2020,Urban Influence Code 2013,County Income Percentile Within State (2021),Bachelor's Degree or Higher Percentage (2018-2022),Vote Percentage
1513,29115,6.2,11.0,0.443478,19.6,76.196298
1271,26135,12.9,12.0,0.024096,13.8,71.112023
885,20049,4.9,7.0,0.028571,18.2,83.761940
836,19149,3.5,2.0,0.909091,24.1,38.539611
1909,37093,8.4,2.0,0.570000,20.2,38.250381
...,...,...,...,...,...,...
2763,49027,3.3,11.0,0.551724,23.6,87.302100
905,20089,2.9,12.0,0.276190,18.5,85.196560
1096,22021,7.7,7.0,0.187500,12.1,83.494330
235,8033,6.3,12.0,0.312500,26.3,75.155280
1061,21191,5.1,1.0,0.716667,16.6,79.638989

In [53]:
# build model - random forest

# train
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_depth=2, random_state=1)
rf.fit(x_train, y_train)

y_rf_train_pred = rf.predict(x_train)
y_rf_test_pred = rf.predict(x_test)

In [54]:
# display data
from sklearn.metrics import mean_squared_error, r2_score

rf_train_mse = mean_squared_error(y_train, y_rf_train_pred)
rf_train_r2 = r2_score(y_train, y_rf_train_pred)

rf_test_mse = mean_squared_error(y_test, y_rf_test_pred)
rf_test_r2 = r2_score(y_test, y_rf_test_pred)

rf_results = pd.DataFrame(["Random Forest", rf_train_mse, rf_train_r2, rf_test_mse, rf_test_r2]).transpose()
rf_results.columns = ["Method", "Training Mean Squared Error", "Training r^2", "Test Mean Squared Error", "Test r^2"]
rf_results

,Method,Training Mean Squared Error,Training r^2,Test Mean Squared Error,Test r^2
0,Random Forest,81325143.711261,0.652269,79002841.965258,0.651475